#!/usr/bin/env bash

# Be sure to run:
# pip3 install pywal haishoku
# brew install wallpaper

WALLPAPER="$(wallpaper get | head -n 1)"

# Set my color theme according to my wallpaper
#
# -q : quiet
# -s : don't set terminal colors (they never look great)
# -n : don't set wallpaper
# -e : skip setting polybar. Important for mac
# -t : skip setting tty colors
#
# Other options to consider:
#
# -b "#191919" : set background
#
wal --saturate 0.63 -q -e -t -n -s --backend haishoku -i "$WALLPAPER"
